# Generated by Django 3.2.25 on 2026-02-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('poster_path', models.CharField(blank=True, default='', max_length=200)),
                ('release_date', models.CharField(blank=True, default='', max_length=20)),
                ('overview', models.TextField(blank=True, default='')),
                ('vote_average', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('want_to_watch', 'Want to Watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want_to_watch', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
